### ISSUE TITLE
Performance characteristics

### ISSUE THREAD

**Issue by richardscarrott** [fregante/many-keys-map#1]
This package seems really useful. I wondered what the performance characteristics of get / set operations are compared to a regular `Map`?

**Comment by fregante** [comment]
`get`/`set` performance might not be the best in class since this package prioritize `Map` compatibility and iterability over raw performance.

Looping however is untouched (for the same reason) so `for-of`, `.entries()`, etc have the same performance as a regular `Map`

**Comment by richardscarrott** [comment]
Thanks for the info.

I've been benchmarking a number of memoize packages by [modifying the benchmarks](https://github.com/caiogondim/fast-memoize.js/blob/master/benchmark/index.js) from [fast-memoize](https://github.com/caiogondim/fast-memoize.js) and it appears that, [in my particular test case](https://gist.github.com/richardscarrott/bc3f2bff540d0e26a630338b399a8bff), `many-keys-map` is faster than `JSON.stringify` using [mem](https://github.com/sindresorhus/mem#readme) -- although I guess the semantics are a little different as `JSON.stringify` matches different instances of the "same" object, but interesting none the less.

<img width="832" alt="Screenshot 2020-05-10 at 21 01 50" src="https://user-images.githubusercontent.com/539309/81509346-d79f1980-9301-11ea-8be9-d79b86de515d.png">

**Comment by fregante** [comment]
Wow, that really is surprising. What’s more surprising is that there’s another module that’s 150x more efficient than `mem`. A function memoized by mem only pretty much includes a Map#get and that’s only lightly improvable.

cc @sindresorhus

**Comment by richardscarrott** [comment]
I took a look at the [nano-memoize](https://github.com/anywhichway/nano-memoize) benchmarks also which are more well rounded. `fast-memoize`'s benchmarks appear to be misleading because they're biased towards a single primitive argument; fast-memoize is one of the slowest when it comes to multiple arguments.

These are the nano-memoize benchmarks w/ `mem` added -- https://gist.github.com/richardscarrott/bc3f2bff540d0e26a630338b399a8bff#file-benchmark2-

I tried the following variations of mem:

Single primitive parameter
```js
// fn(35);
const mFn = mem(fn);
```
<img width="796" alt="Screenshot 2020-05-11 at 09 22 28" src="https://user-images.githubusercontent.com/539309/81540074-069ca600-9369-11ea-8cf0-8266a872bbb6.png">


Single object parameter
```js
// fn({ number: 35 });
const mFn = mem(fn);
const mFnJSONStringify = mem(fn, { cacheKey: JSON.stringify });
const mFnManyKeysMap = mem(fn, {
  cacheKey: (args) => args,
  cache: new ManyKeysMap(),
});
```
<img width="786" alt="Screenshot 2020-05-11 at 09 23 29" src="https://user-images.githubusercontent.com/539309/81540149-2207b100-9369-11ea-9c48-340134aa8aca.png">

Multiple primitive parameters
```js
// fn(35, false);
const mFn = mem(fn, {
  cacheKey: (args) => args.join(","),
});
const mFnJSONStringify = mem(fn, {
  cacheKey: JSON.stringify,
});
const mFnManyKeysMap = mem(fn, {
  cacheKey: (args) => args,
  cache: new ManyKeysMap(),
});
```
<img width="783" alt="Screenshot 2020-05-11 at 09 24 08" src="https://user-images.githubusercontent.com/539309/81540227-3cda2580-9369-11ea-9685-46e642c2596b.png">

Multiple object parameters
```js
// fn(35, { isComplete: true });
const mFnJSONStringify = mem(fn, {
  cacheKey: JSON.stringify,
});
const mFnManyKeysMap = mem(fn, {
  cacheKey: (args) => args,
  cache: new ManyKeysMap(),
});
```
<img width="785" alt="Screenshot 2020-05-11 at 09 25 13" src="https://user-images.githubusercontent.com/539309/81540317-5f6c3e80-9369-11ea-8948-3aff2b49ba53.png">


Multiple large object parameters
```js
//  fn(35, {
//    isComplete: false,
//    prop0: "value0",
//    prop1: ["value1", "value2"],
//    prop2: ["value3", { prop3: "value4" }],
//    prop4: "value5",
//    prop5: undefined,
//  });
const mFnJSONStringify = mem(fn, {
  cacheKey: JSON.stringify,
});
const mFnManyKeysMap = mem(fn, {
  cacheKey: (args) => args,
  cache: new ManyKeysMap(),
});
```
<img width="783" alt="Screenshot 2020-05-11 at 09 25 40" src="https://user-images.githubusercontent.com/539309/81540356-7317a500-9369-11ea-9f81-545bb64ea85a.png">

It turns out, from these results `many-keys-map` is only faster than `JSON.stringify` when one of the object arguments is large(ish).

The reason I've been looking into this is because imo `mem` has by far the best ergonomics, where the combination of `cacheKey` and `cache` (thanks to many-keys-map) can handle any scenario I've thought of. Just not sure memoization is one of those cases where ergonomics should outweigh performance.

It would be interesting to see if a) the performance difference is significant in real world scenarios and b) if mem can be optimised to come closer to nano / micro -- not quite sure what sort of techniques they're using.

**Comment by fregante** [comment]
If you need to work with objects you can also try https://github.com/fregante/many-keys-weak-map, https://github.com/futpib/deep-weak-map or any Map-like implementation I listed here: https://github.com/sindresorhus/module-requests/issues/108#issuecomment-349596727

How is nano-memoize even serializing that fast?

**Comment by richardscarrott** [comment]
Wow, loads of map implementations to try!

I just tried [deep-weak-map](https://github.com/futpib/deep-weak-map ) and also found [deepmap](https://github.com/barneycarroll/deepmap) -- the latter can't even be required [without editing the source 😂](https://github.com/barneycarroll/deepmap/blob/master/deepmap.es3.js#L88) but the implementation appears to be quite fast:

Single primitive parameter
<img width="795" alt="Screenshot 2020-05-11 at 21 40 10" src="https://user-images.githubusercontent.com/539309/81609587-0f749280-93d0-11ea-9619-1415b24f7cb4.png">

Single object parameter
<img width="784" alt="Screenshot 2020-05-11 at 21 41 27" src="https://user-images.githubusercontent.com/539309/81609692-3af77d00-93d0-11ea-84d1-87c80dda3810.png">

Multiple primitive parameters
<img width="784" alt="Screenshot 2020-05-11 at 21 42 21" src="https://user-images.githubusercontent.com/539309/81609764-59f60f00-93d0-11ea-9303-15f47caf25bf.png">

Multiple object parameters
<img width="785" alt="Screenshot 2020-05-11 at 21 43 05" src="https://user-images.githubusercontent.com/539309/81609836-73975680-93d0-11ea-92a8-513c2d18ae56.png">

Multiple large object parameters
<img width="782" alt="Screenshot 2020-05-11 at 21 43 43" src="https://user-images.githubusercontent.com/539309/81609924-94f84280-93d0-11ea-8cae-645555b57f56.png">

**Comment by richardscarrott** [comment]
I also tried modifying `deep-weak-map` to use regular `Map`s so it can handle primitive values and that proves to be pretty fast (~13,019,994 ops/sec) for those last two tests -- I guess the tradeoff being, unlike `many-keys-map`, it's not a complete implementation of `Map` as you cannot loop through it.

**Comment by fregante** [comment]
Thanks for this report! It helped improve `mem`
